      Subroutine Type201

! Object: Custom Heating/Cooling Element
! Simulation Studio Model: Type201
! 

! Author: B.Sourek, E.Langerova
! Editor: 
! Date:	 October 29, 2023
! last modified: October 29, 2023
! 
! 
! *** 
! *** Model Parameters 
! *** 
!			Qn	kJ/hr [-Inf;+Inf]
!			Mw_n	kg/hr [-Inf;+Inf]
!			Tw_1n	C [-Inf;+Inf]
!			Tw_2n	C [-Inf;+Inf]
!			cp	kJ/kg.K [-Inf;+Inf]
!			T_Dn	C [-Inf;+Inf]

! *** 
! *** Model Inputs 
! *** 
!			Tw_1	C [-Inf;+Inf]
!			T_D	C [-Inf;+Inf]
!			Mw_in	kg/hr [-Inf;+Inf]

! *** 
! *** Model Outputs 
! *** 
!			Qheat	kJ/hr [-Inf;+Inf]
!			Tw_2	C [-Inf;+Inf]
!			Qcool	kJ/hr [-Inf;+Inf]
!			Mw_out	kg/hr [-Inf;+Inf]

! *** 
! *** Model Derivatives 
! *** 
!			Tw_1	C [-Inf;+Inf]
!			T_D	C [-Inf;+Inf]
!			Mw_in	kg/hr [-Inf;+Inf]

! (Comments and routine interface generated by TRNSYS Simulation Studio)
!************************************************************************

!-----------------------------------------------------------------------------------------------------------------------
! This TRNSYS component skeleton was generated from the TRNSYS studio based on the user-supplied parameters, inputs, 
! outputs, and derivatives.  The user should check the component formulation carefully and add the content to transform
! the parameters, inputs and derivatives into outputs.  Remember, outputs should be the average value over the timestep
! and not the value at the end of the timestep; although in many models these are exactly the same values.  Refer to 
! existing types for examples of using advanced features inside the model (Formats, Labels etc.)
!-----------------------------------------------------------------------------------------------------------------------


      Use TrnsysConstants
      Use TrnsysFunctions

!-----------------------------------------------------------------------------------------------------------------------

!DEC$Attributes DLLexport :: Type201

!-----------------------------------------------------------------------------------------------------------------------
!Trnsys Declarations
      Implicit None

      Double Precision Timestep,Time
      Integer CurrentUnit,CurrentType


!    PARAMETERS
      DOUBLE PRECISION Qn
      DOUBLE PRECISION Mw_n
      DOUBLE PRECISION Tw_1n
      DOUBLE PRECISION Tw_2n
      DOUBLE PRECISION cp
      DOUBLE PRECISION T_Dn

!    INPUTS
      DOUBLE PRECISION Tw_1
      DOUBLE PRECISION T_D
      DOUBLE PRECISION Mw_in
      
!    OUTPUTS
      DOUBLE PRECISION Qheat
      DOUBLE PRECISION Tw_2
      DOUBLE PRECISION Qcool
      DOUBLE PRECISION Mw_out
      
!    TEMP
      DOUBLE PRECISION Tw_m
      DOUBLE PRECISION Twm_n
      DOUBLE PRECISION Mw_n_r
      DOUBLE PRECISION Mw_in_r
      DOUBLE PRECISION cp_r

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Get the Global Trnsys Simulation Variables
      Time=getSimulationTime()
      Timestep=getSimulationTimeStep()
      CurrentUnit = getCurrentUnit()
      CurrentType = getCurrentType()
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Set the Version Number for This Type
      If(getIsVersionSigningTime()) Then
		Call SetTypeVersion(17)
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do Any Last Call Manipulations Here
      If(getIsLastCallofSimulation()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Perform Any "After Convergence" Manipulations That May Be Required at the End of Each Timestep
      If(getIsEndOfTimestep()) Then
		Return
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the "Very First Call of the Simulation Manipulations" Here
      If(getIsFirstCallofSimulation()) Then

		!Tell the TRNSYS Engine How This Type Works
		Call SetNumberofParameters(6)           !The number of parameters that the the model wants
		Call SetNumberofInputs(3)                   !The number of inputs that the the model wants
		Call SetNumberofDerivatives(3)         !The number of derivatives that the the model wants
		Call SetNumberofOutputs(4)                 !The number of outputs that the the model produces
		Call SetIterationMode(1)                             !An indicator for the iteration mode (default=1).  Refer to section 8.4.3.5 of the documentation for more details.
		Call SetNumberStoredVariables(0,0)                   !The number of static variables that the model wants stored in the global storage array and the number of dynamic variables that the model wants stored in the global storage array
		Call SetNumberofDiscreteControls(0)               !The number of discrete control functions set by this model (a value greater than zero requires the user to use Solver 1: Powell's method)

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!Do All of the First Timestep Manipulations Here - There Are No Iterations at the Intial Time
      If (getIsStartTime()) Then
      Qn = getParameterValue(1)
      Mw_n = getParameterValue(2)
      Tw_1n = getParameterValue(3)
      Tw_2n = getParameterValue(4)
      cp = getParameterValue(5)
      T_Dn = getParameterValue(6)

      Tw_1 = GetInputValue(1)
      T_D = GetInputValue(2)
      Mw_in = GetInputValue(3)
      
	
   !Check the Parameters for Problems (#,ErrorType,Text)
   !Sample Code: If( PAR1 <= 0.) Call FoundBadParameter(1,'Fatal','The first parameter provided to this model is not acceptable.')

    If (Mw_in<0.) Call FoundBadParameter(1,'Fatal','The inlet flowrate must be positive.')
    If (Mw_n<0.) Call FoundBadParameter(2,'Fatal','The nominal inlet flowrate must be positive.')
    If (Qn<=0.) Call FoundBadParameter(3,'Fatal','The element nominal power must be positive.')
    If (ErrorFound()) Return
    
   !Set the Initial Values of the Outputs (#,Value)
      Call SetOutputValue(1, Qheat) ! Qheat
      Call SetOutputValue(2, Tw_2) ! Tw_2
      Call SetOutputValue(3, Qcool) ! Qcool
      Call SetOutputValue(4, Mw_in) ! Mw_out


   !If Needed, Set the Initial Values of the Static Storage Variables (#,Value)
   !Sample Code: SetStaticArrayValue(1,0.d0)

   !If Needed, Set the Initial Values of the Dynamic Storage Variables (#,Value)
   !Sample Code: Call SetDynamicArrayValueThisIteration(1,20.d0)

   !If Needed, Set the Initial Values of the Discrete Controllers (#,Value)
   !Sample Code for Controller 1 Set to Off: Call SetDesiredDiscreteControlState(1,0) 

		Return

      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!ReRead the Parameters if Another Unit of This Type Has Been Called Last
      If(getIsReReadParameters()) Then
		!Read in the Values of the Parameters from the Input File
      Qn = getParameterValue(1)
      Mw_n = getParameterValue(2)
      Tw_1n = getParameterValue(3)
      Tw_2n = getParameterValue(4)
      cp = getParameterValue(5)
      T_Dn = getParameterValue(6)

		
      EndIf
!-----------------------------------------------------------------------------------------------------------------------

!Read the Inputs
      Tw_1 = GetInputValue(1)
      T_D = GetInputValue(2)
      Mw_in = GetInputValue(3)
		

	!Check the Inputs for Problems (#,ErrorType,Text)
	!Sample Code: If( IN1 <= 0.) Call FoundBadInput(1,'Fatal','The first input provided to this model is not acceptable.')
 
      If(ErrorFound()) Return
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!    *** PERFORM ALL THE CALCULATION HERE FOR THIS MODEL. ***
!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Previous Control States if Discrete Controllers are Being Used (#)
	!Sample Code: CONTROL_LAST=getPreviousControlState(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Values from the Global Storage Array for the Static Variables (#)
	!Sample Code: STATIC1=getStaticArrayValue(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!If Needed, Get the Initial Values of the Dynamic Variables from the Global Storage Array (#)
	!Sample Code: T_INITIAL_1=getDynamicArrayValueLastTimestep(1)
	!-----------------------------------------------------------------------------------------------------------------------

	!-----------------------------------------------------------------------------------------------------------------------
	!Perform All of the Calculations Here to Set the Outputs from the Model Based on the Inputs


    
     If (Mw_in <= 36) Then
    ! No flow
      Qheat = 0.d0 ! Qheat
      Tw_2 = Tw_1 ! Tw_2
      Qcool = 0.d0 ! Qcool
      Mw_out = 0.d0 ! Mw_out
        
     Else
        Mw_in_r = Mw_in/3600
        Mw_n_r = Mw_n/3600
        cp_r = cp*1000
    ! Cooling or heating ?
     Tw_m = (Tw_1+Tw_2)/2.d0
     Twm_n = (Tw_1n+Tw_2n)/2.d0
     
         If (Tw_m < T_D) Then
            Tw_2 = Tw_1+(Tw_1n-Tw_2n)*(Mw_n_r/Mw_in_r)*((T_D-Tw_m)/(Twm_n-T_Dn))**(1.3)
            Qheat = 0.d0
            Qcool = -Mw_in_r*cp_r*(Tw_1-Tw_2)*(3.6)
         Else
            Tw_2 = Tw_1-(Tw_1n-Tw_2n)*(Mw_n_r/Mw_in_r)*((Tw_m-T_D)/(Twm_n-T_Dn))**(1.3)
            Qcool = 0.d0
            Qheat = Mw_in_r*cp_r*(Tw_1-Tw_2)*(3.6)
         EndIf
        
     EndIf

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
    !Set the Outputs from this Model (#,Value)
      Call SetOutputValue(1, Qheat) ! Qheat
      Call SetOutputValue(2, Tw_2) ! Tw_2
      Call SetOutputValue(3, Qcool) ! Qcool
      Call SetOutputValue(4, Mw_in) ! Mw_out

!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Desired Disceret Control Signal Values for this Iteration (#,State)
!Sample Code:  Call SetDesiredDiscreteControlState(1,1)
!-----------------------------------------------------------------------------------------------------------------------

!-----------------------------------------------------------------------------------------------------------------------
!If Needed, Store the Final value of the Dynamic Variables in the Global Storage Array (#,Value)
!Sample Code:  Call SetDynamicArrayValueThisIteration(1,T_FINAL_1)
!-----------------------------------------------------------------------------------------------------------------------
 
      Return
      End
!-----------------------------------------------------------------------------------------------------------------------
